// Code generated by ifacemaker; DO NOT EDIT.

package cache

import (
	"github.com/thiagozs/go-cache/kind"
)

// CacheRepo ...
type CacheRepo interface {
	WriteKeyVal(key string, val string) error
	WriteKeyValTTL(key string, val string, ttlSeconds int) error
	DeleteKey(key string) (string, error)
	WriteKeyValAsJSON(key string, val interface{}) error
	WriteKeyValAsJSONTTL(key string, val interface{}, ttlSeconds int) error
	GetVal(key string) (string, error)
	GetDriver() kind.Driver
}
