// Code generated by ifacemaker; DO NOT EDIT.

package redis

import (
	"github.com/thiagozs/go-cache/kind"
)

// RedisLayerRepo ...
type RedisLayerRepo interface {
	Ping() (string, error)
	GetVal(key string) (string, error)
	DeleteKey(key string) (string, error)
	WriteKeyVal(key string, val string) error
	WriteKeyValTTL(key string, val string, insec int) error
	WriteKeyValAsJSON(key string, val any) error
	WriteKeyValAsJSONTTL(key string, val any, insec int) error
	GetDriver() kind.Driver
}
